variables:
  CI_ID: $CI_JOB_ID

stages:
  - test
  - deploy-prod

test:
  stage: test
  script:
    - garden --logger-type=basic --env=ci build
    - garden --logger-type=basic --env=ci deploy
    # Wait for github key to get replicated into ns
    - sleep 15
    - garden --logger-type=basic --env=ci test
  after_script:
    - kubectl delete namespace "package-ci-${CI_ID}"

deploy-prod:
  stage: deploy-prod
  rules:
    - if: '$CI_COMMIT_BRANCH == "main"'
      when: manual
  script:
    garden --logger-type=basic --env=prod --yes deploy
