variables:
  CI_ID: $CI_PIPELINE_IID

stages:
  - build
  - test
  - cleanup
  - deploy-prod

build:
  stage: build
  script:
    - echo $PATH
    - ls -la /root/.garden/bin
    - pwd
    - garden --env=ci build

test:
  stage: test
  script:
    - echo $PATH
    - ls -la /root/.garden/bin
    - pwd
    - garden --env=ci test

cleanup-ci-ns:
  stage: cleanup
  rules:
    - when: always
  script:
    - kubectl delete namespace "package-ci-${CI_ID}"

deploy-prod:
  stage: deploy-prod
  rules:
    - if: '$CI_COMMIT_BRANCH == "main"'
      when: manual
  script:
    garden --env=prod --yes deploy
