version: "3.9"
services:
  backend:
    build: ./backend
    command:
      - uvicorn
      - --port=80
      - --host=0.0.0.0
      - routers.main:app
    environment:
      DB_ADDRESS: backend-db
      DB_NAME: cvedb
      DB_PASS: password
      DB_PORT: 5432
      DB_USER: user
      GH_ACCESS_TOKEN: ${GH_ACCESS_TOKEN}
      REDIS_HOST: backend-redis
      REDIS_PORT: 6379
    ports:
      - ${API_PORT:-8001}:80

  backend-db:
    environment:
      POSTGRES_DB: cvedb
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    image: docker.io/postgres:15.0
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend-redis:
    image: docker.io/redis:7.0.5
    ports:
      - 6379:6379

volumes:
  postgres_data:
