version: "3.9"
services:
  lavi-worker:
    build: ./backend
    command:
      - uvicorn
      - --port=80
      - --host=0.0.0.0
      - routers.main:app
    environment:
      DB_ADDRESS: lavi-worker-db
      DB_NAME: cvedb
      DB_PASS: password
      DB_PORT: 5432
      DB_USER: user
      GH_ACCESS_TOKEN: ${GH_ACCESS_TOKEN}
    ports:
      - ${API_PORT:-8001}:80

  lavi-worker-db:
    environment:
      POSTGRES_DB: cvedb
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    image: docker.io/postgres:15.0
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data

  repo-worker-redis:
    image: docker.io/redis:7.0.5
    ports:
      - 6379:6379

volumes:
  postgres_data:
