version: "3.9"
services:
  lavi-worker:
    build: ./backend
    command:
      - uvicorn
      - --port=80
      - --host=0.0.0.0
      - routers.main:app
    environment:
      DB_ADDRESS: lavi-worker-db
      DB_NAME: cvedb
      DB_PASS: password
      DB_PORT: 5432
      DB_USER: user
      GH_ACCESS_TOKEN: ${GH_ACCESS_TOKEN}
      EXPECTED_PREFIX: /api
    ports:
      - ${API_PORT:-8001}

  lavi-worker-db:
    environment:
      POSTGRES_DB: cvedb
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    image: docker.io/postgres:15.0
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data

  repo-worker-redis:
    image: docker.io/redis:7.0.5
    ports:
      - 6379:6379

  repo-worker-api:
    build: ./repo-worker
    command:
      - uvicorn
      - --port=80
      - --host=0.0.0.0
      - repo_worker.api.main:app
    environment:
      REDIS_HOST: repo-worker-redis
      REDIS_PORT: 6379
      LAVI_API_URL: http://lavi-worker
      GH_ACCESS_TOKEN: ${GH_ACCESS_TOKEN}
    ports:
      - 8002:80

  repo-worker-worker-list-packages:
    build: ./repo-worker
    command:
      - python3
      - repo_worker/entrypoint.py
      - --mode=redis
      - list-packages-worker
    deploy:
      replicas: 1
    environment:
      REDIS_HOST: repo-worker-redis
      REDIS_PORT: 6379
      LAVI_API_URL: http://lavi-worker
      GH_ACCESS_TOKEN: ${GH_ACCESS_TOKEN}

  repo-worker-worker-list-versions:
    build: ./repo-worker
    command:
      - python3
      - repo_worker/entrypoint.py
      - --mode=redis
      - list-package-versions
    deploy:
      replicas: 1
    environment:
      REDIS_HOST: repo-worker-redis
      REDIS_PORT: 6379
      LAVI_API_URL: http://lavi-worker
      GH_ACCESS_TOKEN: ${GH_ACCESS_TOKEN}

  repo-worker-worker-generate-trees:
    build: ./repo-worker
    command:
      - python3
      - repo_worker/entrypoint.py
      - --mode=redis
      - generate-tree
    deploy:
      replicas: 5
    environment:
      REDIS_HOST: repo-worker-redis
      REDIS_PORT: 6379
      LAVI_API_URL: http://lavi-worker
      GH_ACCESS_TOKEN: ${GH_ACCESS_TOKEN}

  repo-worker-worker-db-sync-trees:
    build: ./repo-worker
    command:
      - python3
      - repo_worker/entrypoint.py
      - --mode=redis
      - db-sync-trees
    deploy:
      replicas: 1
    environment:
      REDIS_HOST: repo-worker-redis
      REDIS_PORT: 6379
      LAVI_API_URL: http://lavi-worker
      GH_ACCESS_TOKEN: ${GH_ACCESS_TOKEN}

  lavi-docs:
    build: ./docs
    deploy:
      replicas: 1

  nginx:
    depends_on:
        - lavi-docs
        - lavi-worker
    image: nginx:alpine
    restart: always
    volumes:
      - "./nginx.conf:/etc/nginx/nginx.conf"
    ports:
      - 80:80

volumes:
  postgres_data:
