apiVersion: v1
kind: Secret
metadata:
  labels:
    {{- include "lavi-worker.dbLabels" . | nindent 4 }}
  name: {{ include "lavi-worker.dbFullname" . }}
type: Opaque
data:
  # Look into the cluster to see if secret exists, if so use existing admin password, else make new one
  {{- if ((lookup "v1" "Secret" (.Release.Namespace) (include "lavi-worker.dbFullname" .)) | len) }}
  postgresAdminPassword: {{ (lookup "v1" "Secret" (.Release.Namespace) (include "lavi-worker.dbFullname" .)).data.postgresAdminPassword }}
  {{- else }}
  postgresAdminPassword: {{ randAlphaNum 16 | b64enc }}
  {{- end }}
  postgresAdminUser: {{ "admin" | b64enc }}
  postgresDbName: {{ .Values.postgres.dbname | b64enc }}
