apiVersion: v1
kind: Service
metadata:
  labels:
    {{- include "lavi-worker.redisLabels" . | nindent 4 }}
  name: {{ include "lavi-worker.redisFullname" . }}
spec:
  ports:
    - name: redis
      port: 6379
      protocol: TCP
      targetPort: 6379
  selector:
    {{- include "lavi-worker.redisSelectorLabels" . | nindent 4 }}
  type: ClusterIP