apiVersion: v1
kind: Service
metadata:
  labels:
    {{- include "meta-db.labels" . | nindent 4 }}
  name: {{include "meta-db.fullname" . }}
spec:
  ports:
    - name: grpc
      port: 80
      protocol: TCP
      targetPort: 50051
  selector:
    {{- include "meta-db.selectorLabels" . | nindent 4 }}
  type: ClusterIP
