
[tool.poetry]
name = "lavi-temp"
version = "0.0.0"
description = ""
authors = ["LAVI CLI"]

[tool.poetry.dependencies]
python = "^3.10"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
