apiVersion: batch/v1
kind: CronJob
metadata:
  labels:
    {{- include "repo-worker.baseLabels" . | nindent 4 }}
    app.kubernetes.io/component: refresh-queues
  name: {{ printf "%s-refresh" (include "repo-worker.fullname" .) }}
spec:
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - args:
                - "repo_worker/entrypoint.py"
                - "--mode=redis"
                - "refresh-queues"
              command: ["python3"]
              env:
                - name: REDIS_HOST
                  value: {{ printf "%s.%s.svc.cluster.local" (include "repo-worker.redisFullname" .) .Release.Namespace }}
                - name: REDIS_PORT
                  value: "6379"
                - name: LAVI_API_URL
                  value: {{ printf "http://lavi-worker.%s.svc.cluster.local" .Release.Namespace }}
                - name: GH_ACCESS_TOKEN
                  valueFrom:
                    secretKeyRef:
                      key: {{ .Values.ghAccessToken.secretKey }}
                      name: {{ .Values.ghAccessToken.secretName }}
              image: {{ printf "%s:%s" .Values.image.repository .Values.image.tag | quote }}
              imagePullPolicy: {{ .Values.image.pullPolicy }}
              name: worker
          restartPolicy: OnFailure
  schedule: "*/2 * * * *"  # Every 2 minutes
