apiVersion: v1
kind: Service
metadata:
  labels:
    {{- include "repo-worker.baseLabels" . | nindent 4 }}
    app.kubernetes.io/component: api
  name: {{ include "repo-worker.fullname" . }}
spec:
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 80
  selector:
    {{- include "repo-worker.baseSelectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: api
  type: ClusterIP
